version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/mesharialtawfiq.com:/etc/letsencrypt/live/mesharialtawfiq.com
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    build: ./myportfolio
    container_name: frontend
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./admin-protofolio-backend
    container_name: backend
    working_dir: /app
    expose:
      - "3000"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:
    external: true

networks:
  app-network:
    driver: bridge
